import { useEffect, useState } from 'react';
import { getAlerts } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { 
  Bell, AlertOctagon, AlertTriangle, Info, Users, 
  MapPin, Flame, Plus, ShieldAlert, CheckCircle2 
} from 'lucide-react';
import toast from 'react-hot-toast';

export default function Alerts() {
  const { role } = useAuth();
  const [alerts, setAlerts] = useState([]);
  const [summary, setSummary] = useState({ critical: 0, high: 0, medium: 0, active: 0 });
  const [loading, setLoading] = useState(true);
  
  // Custom Alert Form State
  const [showForm, setShowForm] = useState(false);
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [severity, setSeverity] = useState('high');
  const [category, setCategory] = useState('Safety');
  const [district, setDistrict] = useState('District 1');
  const [affectedPopulation, setAffectedPopulation] = useState('');

  const isAuthority = role === 'admin' || role === 'government';

  useEffect(() => {
    async function fetchData() {
      try {
        const response = await getAlerts();
        setAlerts(response.alerts || []);
        setSummary(response.summary || { critical: 0, high: 0, medium: 0, active: 0 });
      } catch (err) {
        console.error(err);
        toast.error('Failed to load active system alerts.');
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, []);

  const handleCreateAlert = (e) => {
    e.preventDefault();
    if (!title || !description || !affectedPopulation) {
      toast.error('Please fill in all alert fields');
      return;
    }

    const newAlert = {
      id: alerts.length + 1,
      severity,
      title,
      description,
      category,
      timestamp: new Date().toISOString(),
      status: 'active',
      district,
      affectedPopulation: parseInt(affectedPopulation) || 0,
    };

    setAlerts([newAlert, ...alerts]);
    setSummary((prev) => ({
      ...prev,
      total: (prev.total || 0) + 1,
      active: (prev.active || 0) + 1,
      [severity]: (prev[severity] || 0) + 1,
    }));

    setTitle('');
    setDescription('');
    setAffectedPopulation('');
    setShowForm(false);
    toast.success('⚠️ Emergency alert dispatched to the community!');
  };

  const getSeverityStyle = (sev) => {
    switch (sev?.toLowerCase()) {
      case 'critical':
        return {
          card: 'border-red-500/35 bg-red-500/5',
          text: 'text-red-400',
          icon: <AlertOctagon className="text-red-400" size={16} />,
          badge: 'bg-red-500/10 text-red-400 border-red-500/20',
        };
      case 'high':
        return {
          card: 'border-orange-500/35 bg-orange-500/5',
          text: 'text-orange-400',
          icon: <AlertTriangle className="text-orange-400" size={16} />,
          badge: 'bg-orange-500/10 text-orange-400 border-orange-500/20',
        };
      case 'medium':
        return {
          card: 'border-yellow-500/35 bg-yellow-500/5',
          text: 'text-yellow-400',
          icon: <AlertTriangle className="text-yellow-400" size={16} />,
          badge: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20',
        };
      default:
        return {
          card: 'border-white/10 bg-surface-900',
          text: 'text-slate-400',
          icon: <Info className="text-slate-400" size={16} />,
          badge: 'bg-white/5 text-slate-400 border-white/10',
        };
    }
  };

  if (loading) {
    return (
      <div className="flex h-[calc(100vh-120px)] items-center justify-center bg-surface-950">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 border-4 border-primary-500/30 border-t-primary-500 rounded-full animate-spin" />
          <p className="text-slate-400 text-sm animate-pulse">Checking community sensors...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 bg-surface-950 text-slate-100 p-1">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold font-display text-slate-100 flex items-center gap-2">
            System Alerts & Dispatch
          </h1>
          <p className="text-xs text-slate-500">Real-time alerts generated by AI sensor modeling and emergency dispatches.</p>
        </div>

        {isAuthority && (
          <button
            onClick={() => setShowForm(!showForm)}
            className="flex items-center gap-1.5 bg-primary-600 hover:bg-primary-500 text-white text-xs font-semibold px-4 py-2.5 rounded-xl transition-all shadow-glow-primary cursor-pointer self-start"
          >
            <Plus size={16} />
            <span>Dispatch Alert</span>
          </button>
        )}
      </div>

      {/* Summary Grid */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-surface-900 border border-white/5 p-4 rounded-2xl flex flex-col justify-between">
          <span className="text-[10px] font-semibold uppercase tracking-wider text-slate-400">Active Warnings</span>
          <h3 className="text-2xl font-bold font-display text-slate-100 mt-2">{summary.active || 0}</h3>
        </div>
        <div className="bg-surface-900 border border-white/5 p-4 rounded-2xl flex flex-col justify-between">
          <span className="text-[10px] font-semibold uppercase tracking-wider text-rose-400">Critical Threats</span>
          <h3 className="text-2xl font-bold font-display text-rose-400 mt-2">{summary.critical || 0}</h3>
        </div>
        <div className="bg-surface-900 border border-white/5 p-4 rounded-2xl flex flex-col justify-between">
          <span className="text-[10px] font-semibold uppercase tracking-wider text-orange-400">High Risks</span>
          <h3 className="text-2xl font-bold font-display text-orange-400 mt-2">{summary.high || 0}</h3>
        </div>
        <div className="bg-surface-900 border border-white/5 p-4 rounded-2xl flex flex-col justify-between">
          <span className="text-[10px] font-semibold uppercase tracking-wider text-emerald-400">Resolved Today</span>
          <h3 className="text-2xl font-bold font-display text-emerald-400 mt-2 flex items-center gap-1.5 mt-2">
            <CheckCircle2 size={20} />
            <span>Operational</span>
          </h3>
        </div>
      </div>

      {/* Custom Alert Dispatch Form */}
      {showForm && (
        <form onSubmit={handleCreateAlert} className="bg-surface-900 border border-primary-500/30 rounded-2xl p-5 space-y-4 max-w-xl animate-slide-up">
          <h3 className="text-sm font-bold text-slate-200 flex items-center gap-2 border-b border-white/5 pb-3">
            <ShieldAlert size={16} className="text-primary-400" />
            Dispatch Emergency Broadcast
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-1">
              <label className="text-[10px] font-semibold text-slate-400 uppercase">Alert Title</label>
              <input
                type="text"
                placeholder="e.g. Pipeline Water Quality Drop"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full bg-surface-800 border border-white/5 focus:border-primary-500/50 rounded-xl px-3 py-2 text-xs text-slate-200 placeholder-slate-500 focus:outline-none"
              />
            </div>
            <div className="space-y-1">
              <label className="text-[10px] font-semibold text-slate-400 uppercase">Severity</label>
              <select
                value={severity}
                onChange={(e) => setSeverity(e.target.value)}
                className="w-full bg-surface-800 border border-white/5 focus:border-primary-500/50 rounded-xl px-3 py-2 text-xs text-slate-200 focus:outline-none"
              >
                <option value="critical">🚨 Critical</option>
                <option value="high">⚠️ High</option>
                <option value="medium">⚡ Medium</option>
                <option value="low">ℹ️ Low</option>
              </select>
            </div>
          </div>

          <div className="space-y-1">
            <label className="text-[10px] font-semibold text-slate-400 uppercase">Description Details</label>
            <textarea
              placeholder="Provide community instructions..."
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              className="w-full bg-surface-800 border border-white/5 focus:border-primary-500/50 rounded-xl px-3 py-2 text-xs text-slate-200 placeholder-slate-500 focus:outline-none h-20 resize-none"
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="space-y-1">
              <label className="text-[10px] font-semibold text-slate-400 uppercase">Category</label>
              <select
                value={category}
                onChange={(e) => setCategory(e.target.value)}
                className="w-full bg-surface-800 border border-white/5 focus:border-primary-500/50 rounded-xl px-3 py-2 text-xs text-slate-200 focus:outline-none"
              >
                <option value="Safety">Safety</option>
                <option value="Environment">Environment</option>
                <option value="Health">Health</option>
                <option value="Infrastructure">Infrastructure</option>
                <option value="Energy">Energy</option>
              </select>
            </div>
            <div className="space-y-1">
              <label className="text-[10px] font-semibold text-slate-400 uppercase">Target District</label>
              <select
                value={district}
                onChange={(e) => setDistrict(e.target.value)}
                className="w-full bg-surface-800 border border-white/5 focus:border-primary-500/50 rounded-xl px-3 py-2 text-xs text-slate-200 focus:outline-none"
              >
                <option value="District 1">District 1</option>
                <option value="District 2">District 2</option>
                <option value="District 3">District 3</option>
                <option value="District 4">District 4</option>
                <option value="Zone B">Zone B</option>
                <option value="Citywide">Citywide</option>
              </select>
            </div>
            <div className="space-y-1">
              <label className="text-[10px] font-semibold text-slate-400 uppercase">Affected Population</label>
              <input
                type="number"
                placeholder="e.g. 15000"
                value={affectedPopulation}
                onChange={(e) => setAffectedPopulation(e.target.value)}
                className="w-full bg-surface-800 border border-white/5 focus:border-primary-500/50 rounded-xl px-3 py-2 text-xs text-slate-200 placeholder-slate-500 focus:outline-none"
              />
            </div>
          </div>

          <div className="flex gap-2 justify-end pt-2">
            <button
              type="button"
              onClick={() => setShowForm(false)}
              className="bg-white/5 hover:bg-white/10 border border-white/5 px-4 py-2 rounded-xl text-xs text-slate-300 font-semibold cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="bg-primary-600 hover:bg-primary-500 text-white px-4 py-2 rounded-xl text-xs font-semibold shadow-glow-primary cursor-pointer"
            >
              Broadcast Alert
            </button>
          </div>
        </form>
      )}

      {/* Alerts Grid List */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {alerts.map((alert) => {
          const style = getSeverityStyle(alert.severity);
          return (
            <div 
              key={alert.id} 
              className={`border rounded-2xl p-5 shadow-lg flex flex-col justify-between transition-all duration-200 ${style.card}`}
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">
                    Category: {alert.category}
                  </span>
                  <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full capitalize border ${style.badge}`}>
                    {alert.severity}
                  </span>
                </div>
                <h3 className="font-bold text-sm text-slate-200 font-display flex items-center gap-2">
                  {style.icon}
                  {alert.title}
                </h3>
                <p className="text-xs text-slate-400 leading-normal">{alert.description}</p>
              </div>

              {/* District & Population Info */}
              <div className="grid grid-cols-2 gap-4 mt-6 border-t border-white/5 pt-4 text-[11px] text-slate-300 font-medium">
                <div className="flex items-center gap-2">
                  <MapPin size={14} className="text-slate-500 shrink-0" />
                  <span>District: {alert.district}</span>
                </div>
                <div className="flex items-center gap-2">
                  <Users size={14} className="text-slate-500 shrink-0" />
                  <span>Affected: {alert.affectedPopulation?.toLocaleString() || '0'}</span>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
